import type { Metadata } from "next";
import { Montserrat, } from "next/font/google";
import "../styles/globals.css";

// Fonts
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Up Lift Foundation",
  description: "Generated by create next app",
  icons: {
    icon: "/uplift-logo.png",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        {children}
      </body>
    </html>
  );
}
